modLoader = "javafml"
loaderVersion = "[4,)"
license = "GNU LGPLv3"

[[mods]]
modId = "biggerstacks"
version = "${file.jarVersion}"
displayName = "Bigger Stacks (Unofficial)"
logoFile = "BiggerStacks.png"
authors = "PORTB"
description = '''Allows increasing stack sizes past 64 up to MAXINT/2 (about 1 billion)'''

[[mixins]]
config = "biggerstacks.mixins.json"

[[dependencies.biggerstacks]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biggerstacks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
